---
output:
  pdf_document: default
  html_document: default
---
#1There is a built-in vector LETTERS contains the uppercase letters of the alphabet and letters which contains the lowercase letters of the alphabet. 
LETTERS #Big Letters
letters #Small Letters


#aYou need to produce a vector that contains the first 11 letters.
Letters_ele <- LETTERS [1:11]
Letters_ele


#bProduce a vector that contains the odd numbered letters.
Letters_odd <- LETTERS [c(1,3,5,7,9,11,13,15,17,19,21,23,25)]
Letters_odd


#cProduce a vector that contains the vowels
Letters_vow <- LETTERS [c(1,5,9,15,21)]
Letters_vow

#dProduce a vector that contains the last 5 lowercase letters.
Letters_low <-LETTERS[c(22:26)]
Letters_low

#eProduce a vector that contains letters between 15 to 24 letters in lowercase.
Letters <- LETTERS [15:24]
Letters

#2.  Create a vector(not a dataframe) with the average temperatures in April for Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.

  AveragetemperaturesApril = c(42, 39, 34, 34, 30, 27)
  AveragetemperaturesApril

#2a.
  CityVector = c( "Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
  CityVector

#2b.
  temperature <- c(42, 39, 34, 34, 30, 27)
  temperature
 
#2c.
  cityTemp <- data.frame(
  CityVector,temperature
  )
  cityTemp

#2d.
  names(cityTemp) <- c("City", "Temperature")
  cityTemp
  
#2e.
str(cityTemp)

#the code displayed the structure of the cityTemp
#it displayed the contents of the data frame and the summary of it.

#2f.
row34 <- cityTemp[3:4, ]
row34

#2g.
highest_Temp <- cityTemp[which.max(cityTemp$Temperature),]
highest_Temp

lowest_Temp <- cityTemp[which.min(cityTemp$Temperature),]
lowest_Temp

#Using Matrices
#2.


#2a. Create a matrix of one to eight and eleven to fourteen with four columns and three rows
matrs <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
matrs  

#2b.
matrsMul <- matrs*2
matrsMul

#2c.
rowTwo <- matrsMul[2, ]
rowTwo

#2d.
rowWanTwo <- matrsMul[c(1,2),c(3,4)]
rowWanTwo

#2e.
colsTworowOne <- matrsMul[3,c(2,3)]
colsTworowOne

#2f.
colsFour <- matrsMul[,4]
colsFour

#2g.
dimnames(matrsMul) <- list(c("isa", "dalawa", "tatlo"), c("uno", "dos", "tres", "quatro"))
matrsMul

#2h.
matrs
dim(matrs) <- c(6,2)
matrs

#Using Arrays

#3a.
values <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
repValues <- rep(values, each = 2)

arra <- array(repValues, dim = c(2,4,3))
arra

#3b.
#it contains three dimensions.

#3c.
dimnames(arra) <- list(
letters [1:2], #names of row
LETTERS [1:4], #names of column
c("1st-Dimensional Array", "2nd-Dimensional-Array", "3rd-Dimensional-Array")
)
array



